# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Korzh\Desktop\SlotMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Korzh\Desktop\SlotMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Korzh\Desktop\SlotMachine\CMakeFiles C:\Users\Korzh\Desktop\SlotMachine\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Korzh\Desktop\SlotMachine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SlotMachine

# Build rule for target.
SlotMachine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SlotMachine
.PHONY : SlotMachine

# fast build rule for target.
SlotMachine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/build
.PHONY : SlotMachine/fast

src/Button.obj: src/Button.cpp.obj
.PHONY : src/Button.obj

# target to build an object file
src/Button.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Button.cpp.obj
.PHONY : src/Button.cpp.obj

src/Button.i: src/Button.cpp.i
.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s
.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/Reel.obj: src/Reel.cpp.obj
.PHONY : src/Reel.obj

# target to build an object file
src/Reel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Reel.cpp.obj
.PHONY : src/Reel.cpp.obj

src/Reel.i: src/Reel.cpp.i
.PHONY : src/Reel.i

# target to preprocess a source file
src/Reel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Reel.cpp.i
.PHONY : src/Reel.cpp.i

src/Reel.s: src/Reel.cpp.s
.PHONY : src/Reel.s

# target to generate assembly for a file
src/Reel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Reel.cpp.s
.PHONY : src/Reel.cpp.s

src/Spin.obj: src/Spin.cpp.obj
.PHONY : src/Spin.obj

# target to build an object file
src/Spin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Spin.cpp.obj
.PHONY : src/Spin.cpp.obj

src/Spin.i: src/Spin.cpp.i
.PHONY : src/Spin.i

# target to preprocess a source file
src/Spin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Spin.cpp.i
.PHONY : src/Spin.cpp.i

src/Spin.s: src/Spin.cpp.s
.PHONY : src/Spin.s

# target to generate assembly for a file
src/Spin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Spin.cpp.s
.PHONY : src/Spin.cpp.s

src/StartSpin.obj: src/StartSpin.cpp.obj
.PHONY : src/StartSpin.obj

# target to build an object file
src/StartSpin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StartSpin.cpp.obj
.PHONY : src/StartSpin.cpp.obj

src/StartSpin.i: src/StartSpin.cpp.i
.PHONY : src/StartSpin.i

# target to preprocess a source file
src/StartSpin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StartSpin.cpp.i
.PHONY : src/StartSpin.cpp.i

src/StartSpin.s: src/StartSpin.cpp.s
.PHONY : src/StartSpin.s

# target to generate assembly for a file
src/StartSpin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StartSpin.cpp.s
.PHONY : src/StartSpin.cpp.s

src/StateMachine.obj: src/StateMachine.cpp.obj
.PHONY : src/StateMachine.obj

# target to build an object file
src/StateMachine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StateMachine.cpp.obj
.PHONY : src/StateMachine.cpp.obj

src/StateMachine.i: src/StateMachine.cpp.i
.PHONY : src/StateMachine.i

# target to preprocess a source file
src/StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StateMachine.cpp.i
.PHONY : src/StateMachine.cpp.i

src/StateMachine.s: src/StateMachine.cpp.s
.PHONY : src/StateMachine.s

# target to generate assembly for a file
src/StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StateMachine.cpp.s
.PHONY : src/StateMachine.cpp.s

src/StopSpin.obj: src/StopSpin.cpp.obj
.PHONY : src/StopSpin.obj

# target to build an object file
src/StopSpin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StopSpin.cpp.obj
.PHONY : src/StopSpin.cpp.obj

src/StopSpin.i: src/StopSpin.cpp.i
.PHONY : src/StopSpin.i

# target to preprocess a source file
src/StopSpin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StopSpin.cpp.i
.PHONY : src/StopSpin.cpp.i

src/StopSpin.s: src/StopSpin.cpp.s
.PHONY : src/StopSpin.s

# target to generate assembly for a file
src/StopSpin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/StopSpin.cpp.s
.PHONY : src/StopSpin.cpp.s

src/Wait.obj: src/Wait.cpp.obj
.PHONY : src/Wait.obj

# target to build an object file
src/Wait.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Wait.cpp.obj
.PHONY : src/Wait.cpp.obj

src/Wait.i: src/Wait.cpp.i
.PHONY : src/Wait.i

# target to preprocess a source file
src/Wait.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Wait.cpp.i
.PHONY : src/Wait.cpp.i

src/Wait.s: src/Wait.cpp.s
.PHONY : src/Wait.s

# target to generate assembly for a file
src/Wait.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/Wait.cpp.s
.PHONY : src/Wait.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\SlotMachine.dir\build.make CMakeFiles/SlotMachine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... SlotMachine
	@echo ... src/Button.obj
	@echo ... src/Button.i
	@echo ... src/Button.s
	@echo ... src/Reel.obj
	@echo ... src/Reel.i
	@echo ... src/Reel.s
	@echo ... src/Spin.obj
	@echo ... src/Spin.i
	@echo ... src/Spin.s
	@echo ... src/StartSpin.obj
	@echo ... src/StartSpin.i
	@echo ... src/StartSpin.s
	@echo ... src/StateMachine.obj
	@echo ... src/StateMachine.i
	@echo ... src/StateMachine.s
	@echo ... src/StopSpin.obj
	@echo ... src/StopSpin.i
	@echo ... src/StopSpin.s
	@echo ... src/Wait.obj
	@echo ... src/Wait.i
	@echo ... src/Wait.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

